---
- hosts: build
  gather_facts: true
  gather_subset:
    - min

  roles:
    - build_awx/assert-val
    - build_awx/prerequisites
    - build_awx/awx-operator
    - build_awx/receptor
    - build_awx/python-base
    - build_awx/python-builder
    - build_awx/ansible-runner
    - build_awx/ansible-builder
    - build_awx/awx-ee
    - build_awx/awx

- hosts: deploy
  gather_facts: true
  gather_subset:
    - min

  roles:
    - deploy_awx/assert-val
    - deploy_awx/prerequisites
    - deploy_awx/awx-operator
    - deploy_awx/awx-demo
