---
# awx-ee
- name: create working directory
  ansible.builtin.file:
    state: directory
    path: "{{ BASE_DIR }}/awx-ee"

- name: clone repository
  ansible.builtin.git:
    repo: https://github.com/ansible/awx-ee.git
    dest: "{{ BASE_DIR }}/awx-ee"
    version: "{{ awx_ee_version }}"
    force: true # ビルドでContainerfileに変更があり再実行時にcloneに失敗するため

- name: update Containerfile for receptor version
  ansible.builtin.replace:
    path: "{{ item }}"
    regexp: '(?<=receptor:)[0-9a-z\.]+'
    replace: "{{ receptor_version }}"
  loop:
    - "{{ BASE_DIR }}/awx-ee/Containerfile"
    - "{{ BASE_DIR }}/awx-ee/execution-environment.yml"
  tags:
    - edit_containerfile

- name: build awx-ee
  ansible.builtin.command:
    cmd: tox -edocker
    chdir: "{{ BASE_DIR }}/awx-ee"
  become: true # ないと"ModuleNotFoundError: No module named 'virtualenv.seed.via_app_data'"で動かないため回避策

- name: create custome Dockerfile
  ansible.builtin.copy:
    dest: "{{ BASE_DIR }}/Dockerfile"
    content: |
      FROM quay.io/ansible/awx-ee
      USER 1000
  # ジョブテンプレートで.git以下のファイルでPermissionErrorになる動作の回避のためユーザーIDを指定したコンテナを作成する

- name: build custom runner image and push
  community.docker.docker_image:
    name: "{{ awx_ee_image_repository }}:{{ awx_ee_version }}"
    source: build
    build:
      path: "{{ BASE_DIR }}"
    repository: "{{ awx_ee_image_repository }}:{{ awx_ee_version }}"
    push: true
    force_tag: true
