---
- name: install packages
  ansible.builtin.apt:
    name:
      - make
      - python3-pip
      - python3-venv
      - tox
      - ansible
      # - python3.9 # awx 21.10.2で必要(3.8はNG)
      # - pythnon3-apt
    update_cache: true
  become: true

- name: alternatives python
  community.general.alternatives:
    name: python
    link: /usr/bin/python
    path: /usr/bin/python3
  become: true
  # for build receptor

# - name: alternatives python 3.9
#   community.general.alternatives:
#     name: python3
#     link: /usr/bin/python3
#     path: /usr/bin/python3.9
#   become: true
#   # for build awx 21.10.2 with Python 3.9

- import_tasks: _install_docker.yml
  become: true

# - import_tasks: _install_k3s.yml
#   become: true

- name: install pip packages
  ansible.builtin.pip:
    name:
      - docker==5.0.3
      - build==0.8.0  # recepter v1.2.3で必要
      # - openshift==0.13.1
      # - tox==3.24.5
      # - setuptools_scm==7.1.0  # awxビルド時のブランチ名取得でPython 3.9だと必要。ただしブランチ名から取得するバージョンはパラメタで与えられるので使わない
  become: true

- name: login container registry
  community.docker.docker_login:
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    registry_url: "{{ registry_url | default(omit) }}"
  when:
    - registry_username is defined
    - registry_password is defined

- name: define repository url
  set_fact:
    operator_image_repository: "{{ ((registry_url is defined) | ternary(registry_url, ''), registry_username, 'awx-operator') | path_join }}"
  when: operator_image_repository is not defined

- name: define repository url
  set_fact:
    awx_image_repository: "{{ ((registry_url is defined) | ternary(registry_url, ''), registry_username, 'awx') | path_join }}"
  when: awx_image_repository is not defined

- name: define repository url
  set_fact:
    awx_ee_image_repository: "{{ ((registry_url is defined) | ternary(registry_url, ''), registry_username, 'awx-ee') | path_join }}"
  when: awx_ee_image_repository is not defined
