---
- name: create working directory
  ansible.builtin.file:
    state: directory
    path: "{{ BASE_DIR }}/awx"

- name: create kustomization file
  ansible.builtin.template:
    src: kustomization.yaml.j2
    dest: "{{ BASE_DIR }}/awx/kustomization.yaml"

- name: deploy awx-operator
  ansible.builtin.command:
    cmd: kubectl apply -k .
    chdir: "{{ BASE_DIR }}/awx"
  #todo: 冪等性 (難しいかな)
